import type { Metadata } from 'next'
import { Nunito_Sans, Roboto } from 'next/font/google'
import './globals.css'

const nunito = Nunito_Sans({ subsets: ['cyrillic']})
const roboto = Roboto({ subsets: ['cyrillic'], weight: ['300']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className + " " + roboto.className}>{children}</body>
    </html>
  )
}
